version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
